language: node_js
sudo: required
matrix:
  include:
    - node_js: "0.12"
      script: "npm test"
    - node_js: "4"
      script: "npm run travis"
    - node_js: "10"
      script: "npm run travis"
env:
  - BLUEBIRD_DEBUG=0
